### ISSUE TITLE
WSO2 Synapse-schema

### ISSUE THREAD

**Issue by Eriklommelen** [vklevko/wso2-synapse-schema#1]
Vladimir,

I have found 2 problems in the synapse schema:

In clone are all the attributes unknown:
<clone continueParent="true">
                <send>
                    <endpoint uri="${XtremisImportbestanden_EP.uri}"/>
                </send>
            </clone>

in the endpoint is the uri unknown:

<send>
                <endpoint uri="${XtremisImportbestanden_EP.uri}"/>
 </send>

regards

Erik

**Comment by vklevko** [comment]
messing "continueParent" attribute was added to the schema.

@Eriklommelen could you please be more specific on endpoint. According to configuration docs it shouldn't have uri parameter. Only address has one.
